#!/usr/bin/env bash
set -euo pipefail

export OSS_BACKEND="${OSS_BACKEND:-s3}"
export OSS_PATH_STYLE="${OSS_PATH_STYLE:-1}"
export OSS_ACCESS_KEY_ID="${OSS_ACCESS_KEY_ID:-clippeross}"
export OSS_ACCESS_KEY_SECRET="${OSS_ACCESS_KEY_SECRET:-11111111}"
export OSS_ENDPOINT="${OSS_ENDPOINT:-http://127.0.0.1:9000}"
export OSS_BUCKET="${OSS_BUCKET:-clipper-migration}"
export OSS_UPLOAD_LOCAL_CLIPS="${OSS_UPLOAD_LOCAL_CLIPS:-1}"
export TEMPORAL_TASK_QUEUE_CPU="${TEMPORAL_TASK_QUEUE_CPU:-cpu-tq}"
export TEMPORAL_TASK_QUEUE_GPU="${TEMPORAL_TASK_QUEUE_GPU:-cpu-tq}"
export COLUMBIA_RUN_WHISPERVIDEO="${COLUMBIA_RUN_WHISPERVIDEO:-1}"
export COLUMBIA_EXPORT_JSON="${COLUMBIA_EXPORT_JSON:-1}"
export COLUMBIA_WHISPERVIDEO_CPU_FALLBACK="${COLUMBIA_WHISPERVIDEO_CPU_FALLBACK:-1}"
export PYTHONUNBUFFERED="${PYTHONUNBUFFERED:-1}"
export WHISPERVIDEO_ROOT="${WHISPERVIDEO_ROOT:-/home/rama/project/ai-podcast-clipper-saas/third_party/whisperVideo}"

python -u -m temporal.worker_video
